worlds:
    новый мир:
    - K444PUFQA
    - 1EF2BQHD4
    - H2RDGQO9R
    - FKO670SZR
    galaxy enjoeyer:
    - L998NVCPN
    - H999OVAIA
    '0_0':
    - 5993IVM16
    - K4YYP0R9B
    космоказич:
    - K44G7U3T1
    - 5993IVM16
    - K4YYP0R9B
    nekosmokazich:
    - K6SFBANKL
